#!/usr/bin/env python
# coding: utf-8

# In[86]:


import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
get_ipython().run_line_magic('matplotlib', 'inline')


# In[72]:


data = pd.read_csv('mnist_train.csv')


# In[74]:


data.head()


# In[75]:


a = data.iloc[3,1:].values


# In[76]:


a = a.reshape(28,28).astype('uint8')
plt.imshow(a)


# In[77]:


df_x = data.iloc[:,1:]
df_y = data.iloc[:,0]


# In[87]:


x_train,  x_test,  y_train, y_test = train_test_split(df_x, df_y, test_size = 0.2, random_state=4)


# In[88]:


y_train.head()


# In[100]:


rf = RandomForestClassifier(n_estimators=100)


# In[104]:


rf.fit(x_train, y_train)


# In[103]:


pred = rf.predict(x_test)


# In[106]:


pred


# In[108]:


s = y_test.values
count = 0
for i in range(len(pred)):
    if pred[i] == s[i]:
        count = count+1


# In[109]:


count


# In[110]:


len(pred)


# In[111]:


11630/12000


# In[ ]:




